DROP DATABASE IF EXISTS negocio;

CREATE DATABASE IF NOT EXISTS negocio;

CREATE TABLE clientes(
    IdCliente INTEGER AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(55) NOT NULL,
    Apellido VARCHAR(55) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Identificacion VARCHAR(30) NOT NULL
);